import { Elysia } from "elysia";
import { readFileSync } from "fs";
import { join } from "path";

const UI_DIR = join(import.meta.dir, "..", "ui");

function readUI(name: string): string {
  return readFileSync(join(UI_DIR, name), "utf-8");
}

export const healthRoutes = new Elysia()
  .get("/", ({ redirect }) => redirect("/app"), {
    detail: {
      tags: ["health"],
      summary: "Redirect to bookmark viewer UI",
      description: "Convenience redirect. A plain `GET /` sends the client to the `/app` viewer interface.",
      responses: {
        301: { description: "Redirect to /app" },
      },
    },
  })
  .get("/openapi.json", async ({ redirect }) => redirect("/docs/json"), {
    detail: {
      tags: ["health"],
      summary: "OpenAPI spec (alias for /docs/json)",
      description:
        "Canonical alias that forwards to the spec endpoint generated by @elysiajs/swagger. " +
        "Use `/docs/json` or `/openapi.json` interchangeably.",
      responses: {
        301: { description: "Redirect to /docs/json" },
      },
    },
  })
  .get(
    "/app",
    () =>
      new Response(readUI("app.html"), {
        headers: {
          "Content-Type": "text/html; charset=utf-8",
          "Cache-Control": "no-store",
        },
      }),
    {
      detail: {
        tags: ["health"],
        summary: "Bookmark viewer web UI",
        description:
          "Serves the static single-page bookmark viewer. " +
          "This is the primary UI consumed by the Chrome extension side-panel and direct browser access.",
        responses: {
          200: { description: "HTML page" },
        },
      },
    }
  )
  .get(
    "/categories",
    () =>
      new Response(readUI("categories.html"), {
        headers: {
          "Content-Type": "text/html; charset=utf-8",
          "Cache-Control": "no-store",
        },
      }),
    {
      detail: {
        tags: ["health"],
        summary: "Category management web UI",
        description:
          "Serves the static category/classification management page. " +
          "Allows users to create, rename, reorder, archive, and restore classifications and groups.",
        responses: {
          200: { description: "HTML page" },
        },
      },
    }
  )
  .get(
    "/health",
    () => ({ status: "ok" }),
    {
      detail: {
        tags: ["health"],
        summary: "Health check",
        description:
          "Returns a static `{ status: 'ok' }` response. " +
          "Does not verify database connectivity - use this for liveness probes only. " +
          "A successful response means the HTTP server process is running.",
        responses: {
          200: {
            description: "Server is alive",
            content: {
              "application/json": {
                schema: { type: "object" as const, properties: { status: { type: "string" as const, example: "ok" } } },
              },
            },
          },
        },
      },
    }
  );
