import { Elysia } from "elysia";
import { readFileSync } from "fs";
import { join } from "path";

type HealthRoutesOptions = {
  checkReadiness?: () => Promise<void>;
};

const UI_DIR = join(import.meta.dir, "..", "ui");
const HTML_CSP = [
  "default-src 'self'",
  "script-src 'unsafe-inline'",
  "style-src 'unsafe-inline'",
  "img-src 'self' data: http: https:",
  "connect-src 'self'",
].join("; ");

function readUI(name: string): string {
  return readFileSync(join(UI_DIR, name), "utf-8");
}

function sessionCookie(): string | null {
  const token = process.env.API_TOKEN ?? "";
  if (!token || token === "change_me_please") return null;
  return `bm_session=${encodeURIComponent(token)}; HttpOnly; SameSite=Strict; Path=/`;
}

function htmlResponse(name: string): Response {
  const headers: Record<string, string> = {
    "Content-Type": "text/html; charset=utf-8",
    "Cache-Control": "no-store",
    "Content-Security-Policy": HTML_CSP,
  };
  const cookie = sessionCookie();
  if (cookie) headers["Set-Cookie"] = cookie;
  return new Response(readUI(name), { headers });
}

export function createHealthRoutes({ checkReadiness }: HealthRoutesOptions = {}) {
  return new Elysia()
    .get("/", ({ redirect }) => redirect("/app"), {
      detail: {
        tags: ["health"],
        summary: "Redirect to bookmark viewer UI",
        description: "Convenience redirect. A plain `GET /` sends the client to the `/app` viewer interface.",
        responses: {
          301: { description: "Redirect to /app" },
        },
      },
    })
    .get("/openapi.json", async ({ redirect }) => redirect("/docs/json"), {
      detail: {
        tags: ["health"],
        summary: "OpenAPI spec (alias for /docs/json)",
        description:
          "Canonical alias that forwards to the spec endpoint generated by @elysiajs/swagger. " +
          "Use `/docs/json` or `/openapi.json` interchangeably.",
        responses: {
          301: { description: "Redirect to /docs/json" },
        },
      },
    })
    .get(
      "/app",
      () => htmlResponse("app.html"),
      {
        detail: {
          tags: ["health"],
          summary: "Bookmark viewer web UI",
          description:
            "Serves the static single-page bookmark viewer. " +
            "This is the primary UI consumed by the Chrome extension side-panel and direct browser access.",
          responses: {
            200: { description: "HTML page" },
          },
        },
      }
    )
    .get(
      "/manage-categories",
      () => htmlResponse("categories.html"),
      {
        detail: {
          tags: ["health"],
          summary: "Category management web UI",
          description:
            "Serves the static category and sub-category management page. " +
            "Allows users to create, rename, archive, restore, and collapse categories and sub-categories.",
          responses: {
            200: { description: "HTML page" },
          },
        },
      }
    )
    .get(
      "/manage-tags",
      () => htmlResponse("tags.html"),
      {
        detail: {
          tags: ["health"],
          summary: "Tag management web UI",
          description:
            "Serves the static tag management page. " +
            "Allows users to create, rename, archive, and restore tags with archive guardrails when active bookmarks still use them.",
          responses: {
            200: { description: "HTML page" },
          },
        },
      }
    )
    .get(
      "/health",
      () => ({ status: "ok", check: "liveness" }),
      {
        detail: {
          tags: ["health"],
          summary: "Liveness check",
          description:
            "Returns a static liveness response for the HTTP process only. " +
            "Does not verify database connectivity. Use `/ready` for DB-aware readiness.",
          responses: {
            200: {
              description: "Server process is alive",
              content: {
                "application/json": {
                  schema: {
                    type: "object" as const,
                    properties: {
                      status: { type: "string" as const, example: "ok" },
                      check: { type: "string" as const, example: "liveness" },
                    },
                  },
                },
              },
            },
          },
        },
      }
    )
    .get(
      "/ready",
      async ({ set }) => {
        try {
          await checkReadiness?.();
          return { status: "ok", check: "readiness" };
        } catch {
          set.status = 503;
          return { status: "error", check: "readiness" };
        }
      },
      {
        detail: {
          tags: ["health"],
          summary: "Readiness check",
          description:
            "Verifies the API can reach its MariaDB dependency. " +
            "Use this for container health checks and operational verification before serving DB-backed requests.",
          responses: {
            200: {
              description: "Server is ready to serve DB-backed requests",
              content: {
                "application/json": {
                  schema: {
                    type: "object" as const,
                    properties: {
                      status: { type: "string" as const, example: "ok" },
                      check: { type: "string" as const, example: "readiness" },
                    },
                  },
                },
              },
            },
            503: {
              description: "Database is not reachable yet",
              content: {
                "application/json": {
                  schema: {
                    type: "object" as const,
                    properties: {
                      status: { type: "string" as const, example: "error" },
                      check: { type: "string" as const, example: "readiness" },
                    },
                  },
                },
              },
            },
          },
        },
      }
    );
}
