import { Elysia } from "elysia";
import { readFileSync } from "fs";
import { join } from "path";

type HealthRoutesOptions = {
  checkReadiness?: () => Promise<void>;
};

const UI_DIR = join(import.meta.dir, "..", "ui");

function readUI(name: string): string {
  return readFileSync(join(UI_DIR, name), "utf-8");
}

export function createHealthRoutes({ checkReadiness }: HealthRoutesOptions = {}) {
  return new Elysia()
    .get("/", ({ redirect }) => redirect("/app"), {
      detail: {
        tags: ["health"],
        summary: "Redirect to bookmark viewer UI",
        description: "Convenience redirect. A plain `GET /` sends the client to the `/app` viewer interface.",
        responses: {
          301: { description: "Redirect to /app" },
        },
      },
    })
    .get("/openapi.json", async ({ redirect }) => redirect("/docs/json"), {
      detail: {
        tags: ["health"],
        summary: "OpenAPI spec (alias for /docs/json)",
        description:
          "Canonical alias that forwards to the spec endpoint generated by @elysiajs/swagger. " +
          "Use `/docs/json` or `/openapi.json` interchangeably.",
        responses: {
          301: { description: "Redirect to /docs/json" },
        },
      },
    })
    .get(
      "/app",
      () =>
        new Response(readUI("app.html"), {
          headers: {
            "Content-Type": "text/html; charset=utf-8",
            "Cache-Control": "no-store",
          },
        }),
      {
        detail: {
          tags: ["health"],
          summary: "Bookmark viewer web UI",
          description:
            "Serves the static single-page bookmark viewer. " +
            "This is the primary UI consumed by the Chrome extension side-panel and direct browser access.",
          responses: {
            200: { description: "HTML page" },
          },
        },
      }
    )
    .get(
      "/categories",
      () =>
        new Response(readUI("categories.html"), {
          headers: {
            "Content-Type": "text/html; charset=utf-8",
            "Cache-Control": "no-store",
          },
        }),
      {
        detail: {
          tags: ["health"],
          summary: "Category management web UI",
          description:
            "Serves the static category/classification management page. " +
            "Allows users to create, rename, reorder, archive, and restore classifications and groups.",
          responses: {
            200: { description: "HTML page" },
          },
        },
      }
    )
    .get(
      "/config",
      () => {
        const apiToken = process.env.API_TOKEN ?? "";
        if (!apiToken || apiToken === "change_me_please") {
          return new Response(
            JSON.stringify({ error: "API_TOKEN is not configured on the server" }),
            { status: 503, headers: { "Content-Type": "application/json" } }
          );
        }
        return new Response(JSON.stringify({ apiToken }), {
          headers: { "Content-Type": "application/json" },
        });
      },
      {
        detail: {
          tags: ["health"],
          summary: "Client configuration",
          description:
            "Returns the `API_TOKEN` needed by the browser UI to authenticate its requests. " +
            "This endpoint is auth-exempt so the UI can bootstrap itself on first load. " +
            "Returns `503` if `API_TOKEN` is not yet configured on the server.",
          responses: {
            200: {
              description: "Configuration for browser UI",
              content: {
                "application/json": {
                  schema: {
                    type: "object" as const,
                    properties: {
                      apiToken: { type: "string" as const, description: "Bearer token to send with all API requests" },
                    },
                  },
                },
              },
            },
            503: { description: "API_TOKEN is not configured on the server" },
          },
        },
      }
    )
    .get(
      "/health",
      () => ({ status: "ok", check: "liveness" }),
      {
        detail: {
          tags: ["health"],
          summary: "Liveness check",
          description:
            "Returns a static liveness response for the HTTP process only. " +
            "Does not verify database connectivity. Use `/ready` for DB-aware readiness.",
          responses: {
            200: {
              description: "Server process is alive",
              content: {
                "application/json": {
                  schema: {
                    type: "object" as const,
                    properties: {
                      status: { type: "string" as const, example: "ok" },
                      check: { type: "string" as const, example: "liveness" },
                    },
                  },
                },
              },
            },
          },
        },
      }
    )
    .get(
      "/ready",
      async ({ set }) => {
        try {
          await checkReadiness?.();
          return { status: "ok", check: "readiness" };
        } catch {
          set.status = 503;
          return { status: "error", check: "readiness" };
        }
      },
      {
        detail: {
          tags: ["health"],
          summary: "Readiness check",
          description:
            "Verifies the API can reach its MariaDB dependency. " +
            "Use this for container health checks and operational verification before serving DB-backed requests.",
          responses: {
            200: {
              description: "Server is ready to serve DB-backed requests",
              content: {
                "application/json": {
                  schema: {
                    type: "object" as const,
                    properties: {
                      status: { type: "string" as const, example: "ok" },
                      check: { type: "string" as const, example: "readiness" },
                    },
                  },
                },
              },
            },
            503: {
              description: "Database is not reachable yet",
              content: {
                "application/json": {
                  schema: {
                    type: "object" as const,
                    properties: {
                      status: { type: "string" as const, example: "error" },
                      check: { type: "string" as const, example: "readiness" },
                    },
                  },
                },
              },
            },
          },
        },
      }
    );
}
