import { Elysia, t } from "elysia";
import { swagger } from "@elysiajs/swagger";
import { db } from "./db/client.ts";
import {
  bookmarks,
  tags,
  classifications,
  classificationGroups,
  bookmarkTags,
  bookmarkClassifications,
} from "./db/schema.ts";
import { eq, isNull, isNotNull, like, and, inArray, sql, desc, asc } from "drizzle-orm";
import type { AnyColumn } from "drizzle-orm";
import { readFileSync } from "fs";
import { join } from "path";

const UI_DIR = join(import.meta.dir, "ui");

function readUI(name: string): string {
  // Read from disk on every request so UI changes are always live
  return readFileSync(join(UI_DIR, name), "utf-8");
}


// ---------------------------------------------------------------------------
// Load .env (Bun reads .env automatically but we call it explicitly for clarity)
// ---------------------------------------------------------------------------

const PORT = Number(process.env.API_PORT ?? 11650);

// ---------------------------------------------------------------------------
// Shared plain-JSON-Schema response shapes (used in detail.responses)
// These must be plain objects, not TypeBox types, because Elysia's
// ResponsesObject uses the openapi-types SchemaObject interface.
// ---------------------------------------------------------------------------

const S = {
  str:  (description: string) => ({ type: "string"  as const, description }),
  num:  (description: string) => ({ type: "number"  as const, description }),
  bool: (description: string) => ({ type: "boolean" as const, description }),
  any:  (description: string) => ({ description }),
  nullable: (schema: object) => ({ anyOf: [schema, { type: "null" as const }] }),
  obj: (description: string, properties: Record<string, object>, required?: string[]) =>
    ({ type: "object" as const, description, properties, ...(required ? { required } : {}) }),
  arr: (description: string, items: object) =>
    ({ type: "array" as const, description, items }),
};

const ErrorResp = {
  description: "Error",
  content: { "application/json": { schema: {
    type: "object" as const,
    properties: { error: { type: "string" as const, description: "Human-readable error message" } },
    required: ["error"],
  }}},
};

const OkResp = {
  description: "Success",
  content: { "application/json": { schema: {
    type: "object" as const,
    properties: { ok: { type: "boolean" as const, enum: [true], description: "Always true on success" } },
    required: ["ok"],
  }}},
};

// ---------------------------------------------------------------------------
// Elysia App
// ---------------------------------------------------------------------------

const app = new Elysia()
  // ── Swagger / OpenAPI ──────────────────────────────────────────────────────
  .use(
    swagger({
      path: "/docs",
      documentation: {
        info: {
          title: "Bookmark Manager API",
          version: "0.1.0",
          description:
            "REST API for the Bookmark Manager Chrome extension.\n\n" +
            "Manages bookmarks, tags, classifications, and classification groups.\n\n" +
            "**Data lifecycle:** records are never hard-deleted. All destructive operations " +
            "set an `archivedAt` timestamp and can be reversed with the corresponding `/restore` endpoint.\n\n" +
            "**Timestamps:** stored and returned as UTC. The `archivedAt` field is `null` " +
            "while a record is active and set to a UTC datetime when archived.",
        },
        tags: [
          { name: "health", description: "Health check and UI entry points" },
          { name: "bookmarks", description: "Create, read, update, archive, and restore bookmarks" },
          { name: "tags", description: "Manage tags and attach them to bookmarks" },
          { name: "classifications", description: "Manage classifications (categories) and assign them to bookmarks" },
          { name: "groups", description: "Manage classification groups that organise classifications" },
        ],
      },
    })
  )

  // ── Root redirect ─────────────────────────────────────────────────────────
  .get("/", ({ redirect }) => redirect("/app"), {
    detail: {
      tags: ["health"],
      summary: "Redirect to bookmark viewer UI",
      description: "Convenience redirect. A plain `GET /` sends the client to the `/app` viewer interface.",
      responses: {
        301: { description: "Redirect to /app" },
      },
    },
  })

  // ── OpenAPI JSON alias at /openapi.json ───────────────────────────────────
  .get("/openapi.json", async ({ redirect }) => redirect("/docs/json"), {
    detail: {
      tags: ["health"],
      summary: "OpenAPI spec (alias for /docs/json)",
      description:
        "Canonical alias that forwards to the spec endpoint generated by @elysiajs/swagger. " +
        "Use `/docs/json` or `/openapi.json` interchangeably.",
      responses: {
        301: { description: "Redirect to /docs/json" },
      },
    },
  })

  // ── Bookmark viewer UI ────────────────────────────────────────────────────
  .get(
    "/app",
    () =>
      new Response(readUI("app.html"), {
        headers: {
          "Content-Type": "text/html; charset=utf-8",
          "Cache-Control": "no-store",
        },
      }),
    {
      detail: {
        tags: ["health"],
        summary: "Bookmark viewer web UI",
        description:
          "Serves the static single-page bookmark viewer. " +
          "This is the primary UI consumed by the Chrome extension side-panel and direct browser access.",
        responses: {
          200: { description: "HTML page" },
        },
      },
    }
  )

  // ── Category management UI ────────────────────────────────────────────────
  .get(
    "/categories",
    () =>
      new Response(readUI("categories.html"), {
        headers: {
          "Content-Type": "text/html; charset=utf-8",
          "Cache-Control": "no-store",
        },
      }),
    {
      detail: {
        tags: ["health"],
        summary: "Category management web UI",
        description:
          "Serves the static category/classification management page. " +
          "Allows users to create, rename, reorder, archive, and restore classifications and groups.",
        responses: {
          200: { description: "HTML page" },
        },
      },
    }
  )

  // ── Health ─────────────────────────────────────────────────────────────────
  .get(
    "/health",
    () => ({ status: "ok" }),
    {
      detail: {
        tags: ["health"],
        summary: "Health check",
        description:
          "Returns a static `{ status: 'ok' }` response. " +
          "Does not verify database connectivity — use this for liveness probes only. " +
          "A successful response means the HTTP server process is running.",
        responses: {
          200: {
            description: "Server is alive",
            content: {
              "application/json": {
                schema: { type: "object" as const, properties: { status: { type: "string" as const, example: "ok" } } },
              },
            },
          },
        },
      },
    }
  )

  // ── Tags: GET /tags ────────────────────────────────────────────────────────
  .get(
    "/tags",
    async ({ query }) => {
      const limit = Math.min(Number(query.limit ?? 20), 100);
      const offset = Number(query.offset ?? 0);
      const search = query.query?.trim() ?? "";
      const sort   = query.sort === "alpha" ? "alpha" : "count";

      const where = and(
        isNull(tags.archivedAt),
        search ? like(tags.name, `%${search}%`) : undefined
      );

      const orderBy = sort === "alpha"
        ? [asc(tags.name)]
        : [desc(sql`COUNT(DISTINCT ${bookmarkTags.bookmarkId})`), asc(tags.name)];

      const [rows, [countRow]] = await Promise.all([
        db
          .select({
            id: tags.id,
            name: tags.name,
            bookmarkCount: sql<number>`COUNT(DISTINCT ${bookmarkTags.bookmarkId})`,
          })
          .from(tags)
          .leftJoin(
            bookmarkTags,
            and(
              eq(bookmarkTags.tagId, tags.id),
              // only count active (non-archived) bookmarks
              sql`EXISTS (SELECT 1 FROM bookmarks b WHERE b.id = ${bookmarkTags.bookmarkId} AND b.archived_at IS NULL)`
            )
          )
          .where(where)
          .groupBy(tags.id, tags.name)
          .orderBy(...orderBy)
          .limit(limit)
          .offset(offset),
        db
          .select({ total: sql<number>`COUNT(*)` })
          .from(tags)
          .where(where),
      ]);

      return { items: rows.map(r => ({ ...r, bookmarkCount: Number(r.bookmarkCount) })), total: Number(countRow.total) };
    },
    {
      query: t.Object({
        query:  t.Optional(t.String({ description: "Search term — filters tag names using a LIKE %term% match (case-insensitive)" })),
        limit:  t.Optional(t.String({ description: "Maximum number of tags to return. Default: 20, max: 100" })),
        offset: t.Optional(t.String({ description: "Zero-based offset for pagination. Default: 0" })),
        sort:   t.Optional(t.String({ description: "Sort order. `count` (default) sorts by active bookmark count descending then name ascending. `alpha` sorts alphabetically ascending" })),
      }),
      detail: {
        tags: ["tags"],
        summary: "List / search tags",
        description:
          "Returns a paginated list of active (non-archived) tags.\n\n" +
          "Each item includes a `bookmarkCount` that reflects only **active** (non-archived) bookmarks. " +
          "Archived bookmarks are excluded from the count even if they retain tag associations.\n\n" +
          "**Sorting:**\n" +
          "- `count` (default) — most-used tags first; ties broken alphabetically\n" +
          "- `alpha` — alphabetical A → Z\n\n" +
          "**Search:** pass `query` for a case-insensitive substring match on the tag name.",
        responses: {
          200: {
            description: "Paginated tag list",
            content: {
              "application/json": {
                schema: {
                  type: "object" as const,
                  properties: {
                    items: {
                      type: "array" as const,
                      items: {
                        type: "object" as const,
                        properties: {
                          id:            S.num("Tag ID"),
                          name:          S.str("Tag name"),
                          bookmarkCount: S.num("Number of active bookmarks using this tag"),
                        },
                      },
                    },
                    total: S.num("Total number of tags matching the query (ignoring limit/offset)"),
                  },
                },
              },
            },
          },
        },
      },
    }
  )

  // ── Flag counts: GET /flag-counts ─────────────────────────────────────────
  .get(
    "/flag-counts",
    async () => {
      const [row] = await db
        .select({
          readLater:   sql<number>`SUM(CASE WHEN read_later   = 1 THEN 1 ELSE 0 END)`,
          hotTopic:    sql<number>`SUM(CASE WHEN hot_topic    = 1 THEN 1 ELSE 0 END)`,
          cheatsheets: sql<number>`SUM(CASE WHEN cheatsheets  = 1 THEN 1 ELSE 0 END)`,
          forReview:   sql<number>`SUM(CASE WHEN for_review   = 1 THEN 1 ELSE 0 END)`,
        })
        .from(bookmarks)
        .where(isNull(bookmarks.archivedAt));

      return {
        readLater:   Number(row.readLater   ?? 0),
        hotTopic:    Number(row.hotTopic    ?? 0),
        cheatsheets: Number(row.cheatsheets ?? 0),
        forReview:   Number(row.forReview   ?? 0),
      };
    },
    {
      detail: {
        tags: ["bookmarks"],
        summary: "Count of active bookmarks per flag",
        description:
          "Returns a single aggregated object with the count of **active** (non-archived) bookmarks " +
          "that have each flag set to `true`.\n\n" +
          "Useful for rendering badge counts in the UI sidebar without fetching full bookmark lists.\n\n" +
          "**Flags:**\n" +
          "- `readLater` — bookmarks saved to read later\n" +
          "- `hotTopic` — bookmarks marked as currently relevant\n" +
          "- `cheatsheets` — bookmarks containing reference material\n" +
          "- `forReview` — bookmarks queued for review",
        responses: {
          200: {
            description: "Flag counts for active bookmarks",
            content: {
              "application/json": {
                schema: {
                  type: "object" as const,
                  properties: {
                    readLater:   S.num("Active bookmarks flagged Read Later"),
                    hotTopic:    S.num("Active bookmarks flagged Hot Topic"),
                    cheatsheets: S.num("Active bookmarks flagged Cheatsheet"),
                    forReview:   S.num("Active bookmarks flagged For Review"),
                  },
                },
              },
            },
          },
        },
      },
    }
  )

  // ── Tags: POST /tags ───────────────────────────────────────────────────────
  .post(
    "/tags",
    async ({ body, set }) => {
      const name = body.name.trim();
      if (!name) {
        set.status = 400;
        return { error: "name is required" };
      }

      try {
        const [result] = await db
          .insert(tags)
          .values({ name })
          .$returningId();
        return { id: result.id, name };
      } catch (err: unknown) {
        if (isDupEntry(err)) {
          set.status = 409;
          return { error: "Tag already exists" };
        }
        throw err;
      }
    },
    {
      body: t.Object({
        name: t.String({ description: "Tag name. Must be unique among active tags. Whitespace is trimmed." }),
      }),
      detail: {
        tags: ["tags"],
        summary: "Create a tag",
        description:
          "Creates a new active tag. The name is trimmed of leading/trailing whitespace before saving.\n\n" +
          "Tag names must be unique among **active** tags. Archived tags with the same name do not block creation " +
          "(the uniqueness constraint uses a generated column that is `NULL` when archived).",
        responses: {
          201: {
            description: "Tag created successfully",
            content: {
              "application/json": {
                schema: {
                  type: "object" as const,
                  properties: {
                    id:   S.num("New tag ID"),
                    name: S.str("Trimmed tag name as stored"),
                  },
                },
              },
            },
          },
          400: { ...ErrorResp, description: "Validation error — name is blank after trimming" },
          409: { ...ErrorResp, description: "Conflict — an active tag with this name already exists" },
        },
      },
    }
  )

  // ── Classifications: GET /classifications ─────────────────────────────────
  .get(
    "/classifications",
    async () => {
      const [groups, classRows, countRows] = await Promise.all([
        db
          .select({
            id: classificationGroups.id,
            name: classificationGroups.name,
            order: classificationGroups.order,
          })
          .from(classificationGroups)
          .where(isNull(classificationGroups.archivedAt))
          .orderBy(classificationGroups.order, classificationGroups.name),
        db
          .select({
            id: classifications.id,
            name: classifications.name,
            order: classifications.order,
            groupId: classifications.groupId,
          })
          .from(classifications)
          .where(isNull(classifications.archivedAt))
          .orderBy(classifications.order, classifications.name),
        // Active bookmark counts per classification
        db
          .select({
            classificationId: bookmarkClassifications.classificationId,
            count: sql<number>`COUNT(*)`,
          })
          .from(bookmarkClassifications)
          .innerJoin(bookmarks, and(
            eq(bookmarkClassifications.bookmarkId, bookmarks.id),
            isNull(bookmarks.archivedAt)
          ))
          .groupBy(bookmarkClassifications.classificationId),
      ]);

      const countMap = new Map<number, number>(
        countRows.map((r) => [r.classificationId, Number(r.count)])
      );

      // Build grouped response
      const grouped = groups.map((g) => ({
        ...g,
        classifications: classRows
          .filter((c) => c.groupId === g.id)
          .map((c) => ({ ...c, bookmarkCount: countMap.get(c.id) ?? 0 })),
      }));

      // Ungrouped classifications (no group)
      const ungrouped = classRows
        .filter((c) => c.groupId === null)
        .map((c) => ({ ...c, bookmarkCount: countMap.get(c.id) ?? 0 }));
      if (ungrouped.length > 0) {
        grouped.push({
          id: 0,
          name: "Ungrouped",
          order: 999,
          classifications: ungrouped,
        });
      }

      return { groups: grouped };
    },
    {
      detail: {
        tags: ["classifications"],
        summary: "List all active classifications, grouped",
        description:
          "Returns all active (non-archived) classifications nested inside their parent groups.\n\n" +
          "Groups are sorted by `order` then `name`. Classifications within each group are also " +
          "sorted by `order` then `name`.\n\n" +
          "Classifications that have no group appear under a synthetic **Ungrouped** entry " +
          "(`id: 0`, `order: 999`) appended at the end of the list.\n\n" +
          "Each classification includes a `bookmarkCount` reflecting only active (non-archived) bookmarks. " +
          "This endpoint is intended for filtering/navigation UI — use `GET /classifications/groups` " +
          "for the management view that also includes archived records.",
        responses: {
          200: {
            description: "Grouped classification list",
            content: {
              "application/json": {
                schema: S.obj("Classification groups response", {
                  groups: S.arr("List of active groups (plus synthetic Ungrouped entry if needed)", S.obj("Classification group", {
                    id:    S.num("Group ID (0 = synthetic Ungrouped entry)"),
                    name:  S.str("Group name"),
                    order: S.num("Display sort order"),
                    classifications: S.arr("Classifications in this group", S.obj("Classification", {
                      id:            S.num("Classification ID"),
                      name:          S.str("Classification name"),
                      order:         S.num("Display sort order"),
                      groupId:       S.nullable(S.num("Parent group ID, or null if ungrouped")),
                      bookmarkCount: S.num("Number of active bookmarks using this classification"),
                    })),
                  })),
                }),
              },
            },
          },
        },
      },
    }
  )

  // ── Classifications: POST /classifications ────────────────────────────────
  .post(
    "/classifications",
    async ({ body, set }) => {
      const name = body.name.trim();
      if (!name) {
        set.status = 400;
        return { error: "name is required" };
      }

      let groupId: number | null = body.groupId ?? null;

      // Create a new group if groupName is provided and no groupId
      if (body.groupName && !groupId) {
        const groupName = body.groupName.trim();
        if (groupName) {
          const [g] = await db
            .insert(classificationGroups)
            .values({ name: groupName })
            .$returningId();
          groupId = g.id;
        }
      }

      try {
        const [result] = await db
          .insert(classifications)
          .values({ name, groupId })
          .$returningId();
        return { id: result.id, name, groupId };
      } catch (err: unknown) {
        if (isDupEntry(err)) {
          set.status = 409;
          return { error: "Classification already exists in this group" };
        }
        throw err;
      }
    },
    {
      body: t.Object({
        name:      t.String({ description: "Classification name. Must be unique within the target group. Whitespace is trimmed." }),
        groupId:   t.Optional(t.Nullable(t.Number({ description: "ID of an existing group to assign this classification to. Omit or pass null to leave ungrouped." }))),
        groupName: t.Optional(t.Nullable(t.String({ description: "If provided (and `groupId` is absent), a new group with this name is created and the classification is placed inside it." }))),
      }),
      detail: {
        tags: ["classifications"],
        summary: "Create a classification",
        description:
          "Creates a new active classification.\n\n" +
          "**Group assignment (pick one):**\n" +
          "- `groupId` — assign to an existing group by ID\n" +
          "- `groupName` — create a brand-new group and place the classification inside it (only used when `groupId` is absent)\n" +
          "- Neither — classification is created ungrouped\n\n" +
          "Classification names must be unique **within their group** among active records. " +
          "A classification named `TypeScript` can exist in both `Languages` and `Frameworks` simultaneously. " +
          "Archived classifications with the same name/group do not block creation.",
        responses: {
          201: {
            description: "Classification created",
            content: {
              "application/json": {
                schema: S.obj("Created classification", {
                  id:      S.num("New classification ID"),
                  name:    S.str("Trimmed name as stored"),
                  groupId: S.nullable(S.num("Assigned group ID, or null if ungrouped")),
                }),
              },
            },
          },
          400: { ...ErrorResp, description: "Validation error — name is blank after trimming" },
          409: { ...ErrorResp, description: "Conflict — an active classification with this name already exists in the same group" },
        },
      },
    }
  )

  // ── Bookmarks: POST /bookmarks ────────────────────────────────────────────
  .post(
    "/bookmarks",
    async ({ body, set }) => {
      const url = body.url.trim();
      const title = body.title.trim();

      if (!url || !title) {
        set.status = 400;
        return { error: "url and title are required" };
      }

      // Duplicate detection
      if (!body.allowDuplicate) {
        const existing = await db
          .select({
            id: bookmarks.id,
            url: bookmarks.url,
            title: bookmarks.title,
            createdAt: bookmarks.createdAt,
          })
          .from(bookmarks)
          .where(and(sql`url = ${url}`, isNull(bookmarks.archivedAt)));

        if (existing.length > 0) {
          set.status = 409;
          return {
            error: "Duplicate URL",
            duplicates: existing.map((b) => ({
              id: b.id,
              url: b.url,
              title: b.title,
              createdAt: b.createdAt,
            })),
          };
        }
      }

      // Insert bookmark
      const flags = body.flags ?? {};
      const [result] = await db
        .insert(bookmarks)
        .values({
          url,
          title,
          description: body.description ?? null,
          faviconUrl: body.faviconUrl ?? null,
          readLater: flags.readLater ? 1 : 0,
          hotTopic: flags.hotTopic ? 1 : 0,
          cheatsheets: flags.cheatsheets ? 1 : 0,
          forReview: flags.forReview ? 1 : 0,
          archivedAt: flags.archived ? sql`NOW()` : null,
        })
        .$returningId();

      const bookmarkId = result.id;

      // Insert tag associations
      const tagIds = [...new Set(body.tags ?? [])].filter(Boolean);
      if (tagIds.length > 0) {
        await db
          .insert(bookmarkTags)
          .values(tagIds.map((tagId) => ({ bookmarkId, tagId })));
      }

      // Insert classification associations
      const classIds = [
        ...new Set(body.classificationIds ?? []),
      ].filter(Boolean);
      if (classIds.length > 0) {
        await db
          .insert(bookmarkClassifications)
          .values(classIds.map((classificationId) => ({ bookmarkId, classificationId })));
      }

      // Return the created bookmark
      const [created] = await db
        .select({
          id: bookmarks.id,
          url: bookmarks.url,
          title: bookmarks.title,
          createdAt: bookmarks.createdAt,
        })
        .from(bookmarks)
        .where(eq(bookmarks.id, bookmarkId));

      set.status = 201;
      return created;
    },
    {
      body: t.Object({
        url:               t.String({ description: "Full URL of the page to bookmark. Whitespace is trimmed. Required." }),
        title:             t.String({ description: "Page title. Whitespace is trimmed. Required." }),
        description:       t.Optional(t.String({ description: "Optional freeform notes or description for the bookmark." })),
        classificationIds: t.Optional(t.Array(t.Number(), { description: "IDs of classifications to attach. Duplicates are deduplicated automatically." })),
        tags:              t.Optional(t.Array(t.Number(), { description: "IDs of tags to attach. Duplicates are deduplicated automatically." })),
        flags: t.Optional(
          t.Object({
            readLater:   t.Optional(t.Boolean({ description: "Flag this bookmark as Read Later." })),
            hotTopic:    t.Optional(t.Boolean({ description: "Flag this bookmark as a Hot Topic." })),
            cheatsheets: t.Optional(t.Boolean({ description: "Flag this bookmark as a Cheatsheet." })),
            forReview:   t.Optional(t.Boolean({ description: "Flag this bookmark as needing Review." })),
            archived:    t.Optional(t.Boolean({ description: "If true, the bookmark is created already archived (archivedAt set to NOW())." })),
          })
        ),
        faviconUrl:     t.Optional(t.String({ description: "URL of the page favicon, typically captured by the extension at save time." })),
        allowDuplicate: t.Optional(t.Boolean({ description: "Set to true to bypass the duplicate URL check and allow saving the same URL more than once." })),
      }),
      detail: {
        tags: ["bookmarks"],
        summary: "Create a bookmark",
        description:
          "Saves a new bookmark with optional tags, classifications, and flags.\n\n" +
          "**Duplicate detection:** by default, if an active bookmark with the same URL already exists " +
          "a `409` is returned with a `duplicates` array listing the existing records. " +
          "Pass `allowDuplicate: true` to skip this check and save regardless.\n\n" +
          "**Tags and classifications** must already exist; pass their integer IDs in `tags` and " +
          "`classificationIds`. Duplicates in those arrays are silently deduplicated.\n\n" +
          "**Flags** are all `false` by default. The special `flags.archived` field allows the " +
          "Chrome extension to save a bookmark directly into the archived state (e.g. when importing " +
          "historical data).",
        responses: {
          201: {
            description: "Bookmark created",
            content: {
              "application/json": {
                schema: S.obj("Created bookmark", {
                  id:        S.num("New bookmark ID"),
                  url:       S.str("Stored URL"),
                  title:     S.str("Stored title"),
                  createdAt: S.any("Creation timestamp (UTC)"),
                }),
              },
            },
          },
          400: { ...ErrorResp, description: "Validation error — url or title is blank after trimming" },
          409: {
            description: "Duplicate URL detected. The response body includes the existing active bookmarks with that URL.",
            content: {
              "application/json": {
                schema: S.obj("Duplicate conflict", {
                  error:      S.str("Error message"),
                  duplicates: S.arr("Existing active bookmarks with the same URL", S.obj("Existing bookmark", {
                    id:        S.num("Bookmark ID"),
                    url:       S.str("URL"),
                    title:     S.str("Title"),
                    createdAt: S.any("Creation timestamp (UTC)"),
                  })),
                }),
              },
            },
          },
        },
      },
    }
  )

  // ── Bookmarks: GET /bookmarks ─────────────────────────────────────────────
  .get(
    "/bookmarks",
    async ({ query }) => {
      const limit = Math.min(Number(query.limit ?? 20), 100);
      const offset = Number(query.offset ?? 0);
      const classificationId = query.classificationId ? Number(query.classificationId) : null;
      const tagId            = query.tagId            ? Number(query.tagId)            : null;
      const flag             = query.flag ?? null; // readLater | hotTopic | cheatsheets | forReview
      const sortBy           = query.sortBy === "oldest" ? "oldest" : "newest";
      const showArchived     = query.archived === "true";

      const orderCol = sortBy === "oldest" ? asc(bookmarks.createdAt) : desc(bookmarks.createdAt);

      // Build all WHERE conditions
      const conditions = [
        showArchived ? isNotNull(bookmarks.archivedAt) : isNull(bookmarks.archivedAt),
      ];

      // Flag filter — map flag name to column
      const flagColMap: Record<string, AnyColumn> = {
        readLater:   bookmarks.readLater,
        hotTopic:    bookmarks.hotTopic,
        cheatsheets: bookmarks.cheatsheets,
        forReview:   bookmarks.forReview,
      };
      if (flag && flagColMap[flag]) {
        conditions.push(eq(flagColMap[flag], 1));
      }

      // Classification filter — subquery
      if (classificationId) {
        const matchingIds = db
          .select({ bookmarkId: bookmarkClassifications.bookmarkId })
          .from(bookmarkClassifications)
          .where(eq(bookmarkClassifications.classificationId, classificationId));
        conditions.push(inArray(bookmarks.id, matchingIds));
      }

      // Tag filter — subquery
      if (tagId) {
        const matchingIds = db
          .select({ bookmarkId: bookmarkTags.bookmarkId })
          .from(bookmarkTags)
          .where(eq(bookmarkTags.tagId, tagId));
        conditions.push(inArray(bookmarks.id, matchingIds));
      }

      const where = and(...conditions);

      const bookmarkCols = {
        id: bookmarks.id,
        url: bookmarks.url,
        title: bookmarks.title,
        description: bookmarks.description,
        faviconUrl: bookmarks.faviconUrl,
        readLater: bookmarks.readLater,
        hotTopic: bookmarks.hotTopic,
        cheatsheets: bookmarks.cheatsheets,
        forReview: bookmarks.forReview,
        createdAt: bookmarks.createdAt,
        updatedAt: bookmarks.updatedAt,
        archivedAt: bookmarks.archivedAt,
      };

      const [rows, [{ total }]] = await Promise.all([
        db.select(bookmarkCols).from(bookmarks).where(where).orderBy(orderCol).limit(limit).offset(offset),
        db.select({ total: sql<number>`COUNT(*)` }).from(bookmarks).where(where),
      ]);

      // Attach tags + classifications to each bookmark
      const ids = rows.map((r) => r.id);
      const [tagRows, classRows] =
        ids.length > 0
          ? await Promise.all([
              db
                .select({
                  bookmarkId: bookmarkTags.bookmarkId,
                  tagId: tags.id,
                  tagName: tags.name,
                })
                .from(bookmarkTags)
                .innerJoin(tags, eq(bookmarkTags.tagId, tags.id))
                .where(inArray(bookmarkTags.bookmarkId, ids)),
              db
                .select({
                  bookmarkId: bookmarkClassifications.bookmarkId,
                  classId: classifications.id,
                  className: classifications.name,
                  groupId: classificationGroups.id,
                  groupName: classificationGroups.name,
                })
                .from(bookmarkClassifications)
                .innerJoin(classifications, eq(bookmarkClassifications.classificationId, classifications.id))
                .leftJoin(classificationGroups, eq(classifications.groupId, classificationGroups.id))
                .where(inArray(bookmarkClassifications.bookmarkId, ids)),
            ])
          : [[], []];

      const items = rows.map((b) => ({
        ...b,
        tags: tagRows
          .filter((t) => t.bookmarkId === b.id)
          .map((t) => ({ id: t.tagId, name: t.tagName })),
        classifications: classRows
          .filter((c) => c.bookmarkId === b.id)
          .map((c) => ({ id: c.classId, name: c.className, groupId: c.groupId ?? null, groupName: c.groupName ?? null })),
      }));

      return { items, total: Number(total) };
    },
    {
      query: t.Object({
        limit:            t.Optional(t.String({ description: "Maximum number of bookmarks to return. Default: 20, max: 100." })),
        offset:           t.Optional(t.String({ description: "Zero-based pagination offset. Default: 0." })),
        classificationId: t.Optional(t.String({ description: "Filter to bookmarks assigned to this classification ID." })),
        tagId:            t.Optional(t.String({ description: "Filter to bookmarks that have this tag ID attached." })),
        flag:             t.Optional(t.String({ description: "Filter to bookmarks with a specific flag set. Allowed values: `readLater`, `hotTopic`, `cheatsheets`, `forReview`." })),
        sortBy:           t.Optional(t.String({ description: "Sort order by creation date. `newest` (default) returns most recent first; `oldest` returns oldest first." })),
        archived:         t.Optional(t.String({ description: "Pass `true` to return archived bookmarks instead of active ones. By default only active bookmarks are returned." })),
      }),
      detail: {
        tags: ["bookmarks"],
        summary: "List bookmarks",
        description:
          "Returns a paginated list of bookmarks with their full tag and classification associations.\n\n" +
          "**Default behaviour:** returns active (non-archived) bookmarks, newest first, 20 per page.\n\n" +
          "**Filters (all combinable with AND logic):**\n" +
          "- `classificationId` — bookmarks assigned to that classification\n" +
          "- `tagId` — bookmarks that have that tag\n" +
          "- `flag` — bookmarks with that flag set (`readLater` | `hotTopic` | `cheatsheets` | `forReview`)\n" +
          "- `archived=true` — show archived bookmarks (mutually exclusive with active)\n\n" +
          "Each bookmark item includes a fully resolved `tags` array and `classifications` array " +
          "(with parent group name). Flags are returned as `0`/`1` integers.",
        responses: {
          200: {
            description: "Paginated bookmark list",
            content: {
              "application/json": {
                schema: S.obj("Bookmark list response", {
                  items: S.arr("Bookmark records", S.obj("Bookmark", {
                    id:          S.num("Bookmark ID"),
                    url:         S.str("Page URL"),
                    title:       S.str("Page title"),
                    description: S.nullable(S.str("Optional notes")),
                    faviconUrl:  S.nullable(S.str("Favicon URL")),
                    readLater:   S.num("Read Later flag (0 or 1)"),
                    hotTopic:    S.num("Hot Topic flag (0 or 1)"),
                    cheatsheets: S.num("Cheatsheet flag (0 or 1)"),
                    forReview:   S.num("For Review flag (0 or 1)"),
                    createdAt:   S.any("Creation timestamp (UTC)"),
                    updatedAt:   S.any("Last-updated timestamp (UTC)"),
                    archivedAt:  S.nullable(S.any("Archive timestamp (UTC), null when active")),
                    tags: S.arr("Attached tags", S.obj("Tag", {
                      id:   S.num("Tag ID"),
                      name: S.str("Tag name"),
                    })),
                    classifications: S.arr("Attached classifications", S.obj("Classification", {
                      id:        S.num("Classification ID"),
                      name:      S.str("Classification name"),
                      groupId:   S.nullable(S.num("Parent group ID")),
                      groupName: S.nullable(S.str("Parent group name")),
                    })),
                  })),
                  total: S.num("Total matching bookmarks (ignoring limit/offset)"),
                }),
              },
            },
          },
        },
      },
    }
  )

  // ── Bookmarks: PATCH /bookmarks/:id ──────────────────────────────────────
  .patch(
    "/bookmarks/:id",
    async ({ params, body, set }) => {
      const id = Number(params.id);
      const [row] = await db.select({ id: bookmarks.id }).from(bookmarks).where(eq(bookmarks.id, id));
      if (!row) { set.status = 404; return { error: "Bookmark not found" }; }

      // Build update object from provided fields
      const updates: Record<string, unknown> = {};
      if (body.title !== undefined) {
        const t = body.title.trim();
        if (!t) { set.status = 400; return { error: "title cannot be empty" }; }
        updates.title = t;
      }
      if (body.url !== undefined) {
        const u = body.url.trim();
        if (!u) { set.status = 400; return { error: "url cannot be empty" }; }
        updates.url = u;
      }
      if (body.description !== undefined) updates.description = body.description ?? null;
      if (body.flags !== undefined) {
        const f = body.flags;
        if (f.readLater   !== undefined) updates.readLater   = f.readLater   ? 1 : 0;
        if (f.hotTopic    !== undefined) updates.hotTopic    = f.hotTopic    ? 1 : 0;
        if (f.cheatsheets !== undefined) updates.cheatsheets = f.cheatsheets ? 1 : 0;
        if (f.forReview   !== undefined) updates.forReview   = f.forReview   ? 1 : 0;
      }

      const changedAssociations =
        body.tagIds !== undefined || body.classificationIds !== undefined;

      if (Object.keys(updates).length > 0) {
        await db.update(bookmarks).set(updates).where(eq(bookmarks.id, id));
      } else if (changedAssociations) {
        await db.update(bookmarks).set({ updatedAt: sql`CURRENT_TIMESTAMP` }).where(eq(bookmarks.id, id));
      }

      // Replace tags if provided
      if (body.tagIds !== undefined) {
        await db.delete(bookmarkTags).where(eq(bookmarkTags.bookmarkId, id));
        const uniqueTagIds = [...new Set(body.tagIds)].filter(Boolean);
        if (uniqueTagIds.length > 0) {
          await db.insert(bookmarkTags).values(uniqueTagIds.map(tagId => ({ bookmarkId: id, tagId })));
        }
      }

      // Replace classifications if provided
      if (body.classificationIds !== undefined) {
        await db.delete(bookmarkClassifications).where(eq(bookmarkClassifications.bookmarkId, id));
        const uniqueClassIds = [...new Set(body.classificationIds)].filter(Boolean);
        if (uniqueClassIds.length > 0) {
          await db.insert(bookmarkClassifications).values(uniqueClassIds.map(classificationId => ({ bookmarkId: id, classificationId })));
        }
      }

      return { ok: true };
    },
    {
      body: t.Object({
        title:             t.Optional(t.String({ description: "New title. Whitespace is trimmed. Cannot be set to an empty string." })),
        url:               t.Optional(t.String({ description: "New URL. Whitespace is trimmed. Cannot be set to an empty string." })),
        description:       t.Optional(t.Nullable(t.String({ description: "New description. Pass null to clear the existing description." }))),
        tagIds:            t.Optional(t.Array(t.Number(), { description: "Replacement tag ID list. When provided, ALL existing tag associations are replaced with this set. Pass an empty array to remove all tags." })),
        classificationIds: t.Optional(t.Array(t.Number(), { description: "Replacement classification ID list. When provided, ALL existing classification associations are replaced with this set. Pass an empty array to remove all classifications." })),
        flags: t.Optional(t.Object({
          readLater:   t.Optional(t.Boolean({ description: "Set or clear the Read Later flag." })),
          hotTopic:    t.Optional(t.Boolean({ description: "Set or clear the Hot Topic flag." })),
          cheatsheets: t.Optional(t.Boolean({ description: "Set or clear the Cheatsheet flag." })),
          forReview:   t.Optional(t.Boolean({ description: "Set or clear the For Review flag." })),
        })),
      }),
      detail: {
        tags: ["bookmarks"],
        summary: "Edit a bookmark",
        description:
          "Partially updates a bookmark. Only fields present in the request body are changed — " +
          "omitting a field leaves its current value untouched.\n\n" +
          "**Tag and classification replacement:** when `tagIds` or `classificationIds` are provided, " +
          "the existing associations are **fully replaced** (not merged). " +
          "Send an empty array to detach all tags or classifications.\n\n" +
          "**Flags:** each flag is independent. Omitting a flag key leaves it unchanged. " +
          "Pass `false` to clear a flag that was previously set.\n\n" +
          "**URL:** when provided, whitespace is trimmed and an empty string is rejected with 400.\n\n" +
          "The `updatedAt` timestamp is maintained automatically. Any bookmark edit, including tag/classification replacement, refreshes it.",
        responses: {
          200: { ...OkResp, description: "Bookmark updated successfully" },
          400: { ...ErrorResp, description: "Validation error — title was provided but is blank after trimming" },
          404: { ...ErrorResp, description: "Bookmark not found" },
        },
      },
    }
  )

  // ── Bookmarks: PATCH /bookmarks/:id/archive ──────────────────────────────
  .patch(
    "/bookmarks/:id/archive",
    async ({ params, set }) => {
      const id = Number(params.id);
      const [row] = await db.select({ id: bookmarks.id, archivedAt: bookmarks.archivedAt })
        .from(bookmarks).where(eq(bookmarks.id, id));
      if (!row) { set.status = 404; return { error: "Bookmark not found" }; }
      if (row.archivedAt) { set.status = 409; return { error: "Already archived" }; }
      await db.update(bookmarks).set({ archivedAt: sql`NOW()` }).where(eq(bookmarks.id, id));
      return { ok: true };
    },
    {
      detail: {
        tags: ["bookmarks"],
        summary: "Archive a bookmark",
        description:
          "Soft-deletes a bookmark by setting its `archivedAt` timestamp to the current UTC time. " +
          "The bookmark record is preserved and can be fully restored via `PATCH /bookmarks/:id/restore`.\n\n" +
          "Archived bookmarks are excluded from `GET /bookmarks` by default and do not appear in flag counts. " +
          "Tag and classification associations are retained during archiving.",
        responses: {
          200: { ...OkResp, description: "Bookmark archived" },
          404: { ...ErrorResp, description: "Bookmark not found" },
          409: { ...ErrorResp, description: "Bookmark is already archived" },
        },
      },
    }
  )

  // ── Bookmarks: PATCH /bookmarks/:id/restore ───────────────────────────────
  .patch(
    "/bookmarks/:id/restore",
    async ({ params, set }) => {
      const id = Number(params.id);
      const [row] = await db.select({ id: bookmarks.id, archivedAt: bookmarks.archivedAt })
        .from(bookmarks).where(eq(bookmarks.id, id));
      if (!row) { set.status = 404; return { error: "Bookmark not found" }; }
      if (!row.archivedAt) { set.status = 409; return { error: "Not archived" }; }
      await db.update(bookmarks).set({ archivedAt: null }).where(eq(bookmarks.id, id));
      return { ok: true };
    },
    {
      detail: {
        tags: ["bookmarks"],
        summary: "Restore an archived bookmark",
        description:
          "Reverses an archive operation by clearing the `archivedAt` timestamp (sets it to `null`). " +
          "The bookmark immediately becomes active again and reappears in standard queries.\n\n" +
          "All tag and classification associations that were present at archive time are still intact.",
        responses: {
          200: { ...OkResp, description: "Bookmark restored to active" },
          404: { ...ErrorResp, description: "Bookmark not found" },
          409: { ...ErrorResp, description: "Bookmark is not archived — cannot restore an active bookmark" },
        },
      },
    }
  )

  // ── Classifications: PATCH /classifications/:id/archive ───────────────────
  .patch(
    "/classifications/:id/archive",
    async ({ params, set }) => {
      const id = Number(params.id);
      const [row] = await db.select({ id: classifications.id, archivedAt: classifications.archivedAt })
        .from(classifications).where(eq(classifications.id, id));
      if (!row) { set.status = 404; return { error: "Classification not found" }; }
      if (row.archivedAt) { set.status = 409; return { error: "Already archived" }; }

      // Block if active bookmarks are linked
      const [{ count }] = await db
        .select({ count: sql<number>`COUNT(*)` })
        .from(bookmarkClassifications)
        .innerJoin(bookmarks, and(
          eq(bookmarkClassifications.bookmarkId, bookmarks.id),
          isNull(bookmarks.archivedAt)
        ))
        .where(eq(bookmarkClassifications.classificationId, id));
      const n = Number(count);
      if (n > 0) {
        set.status = 409;
        return { error: `Cannot archive: ${n} active bookmark${n === 1 ? "" : "s"} linked to this classification` };
      }

      await db.update(classifications).set({ archivedAt: sql`NOW()` }).where(eq(classifications.id, id));
      return { ok: true };
    },
    {
      detail: {
        tags: ["classifications"],
        summary: "Archive a classification",
        description:
          "Soft-deletes a classification by setting its `archivedAt` timestamp.\n\n" +
          "**Safety check:** archiving is blocked if any **active** (non-archived) bookmarks are currently " +
          "assigned to this classification. The error message reports the exact count. " +
          "Reassign or archive those bookmarks first, then retry.\n\n" +
          "Archived classifications no longer appear in `GET /classifications` " +
          "but remain visible in `GET /classifications/groups` for management purposes.",
        responses: {
          200: { ...OkResp, description: "Classification archived" },
          404: { ...ErrorResp, description: "Classification not found" },
          409: { ...ErrorResp, description: "Already archived, or active bookmarks are linked to this classification" },
        },
      },
    }
  )

  // ── Classifications: PATCH /classifications/:id/restore ───────────────────
  .patch(
    "/classifications/:id/restore",
    async ({ params, set }) => {
      const id = Number(params.id);
      const [row] = await db.select({ id: classifications.id, archivedAt: classifications.archivedAt })
        .from(classifications).where(eq(classifications.id, id));
      if (!row) { set.status = 404; return { error: "Classification not found" }; }
      if (!row.archivedAt) { set.status = 409; return { error: "Not archived" }; }
      await db.update(classifications).set({ archivedAt: null }).where(eq(classifications.id, id));
      return { ok: true };
    },
    {
      detail: {
        tags: ["classifications"],
        summary: "Restore an archived classification",
        description:
          "Clears the `archivedAt` timestamp on a classification, making it active again. " +
          "The classification reappears in `GET /classifications` and can be assigned to new bookmarks.\n\n" +
          "Note: if the parent group is also archived, the classification will be restored but its group " +
          "will still be hidden from the active view until the group is also restored.",
        responses: {
          200: { ...OkResp, description: "Classification restored to active" },
          404: { ...ErrorResp, description: "Classification not found" },
          409: { ...ErrorResp, description: "Classification is not archived" },
        },
      },
    }
  )

  // ── Tags: PATCH /tags/:id/archive ─────────────────────────────────────────
  .patch(
    "/tags/:id/archive",
    async ({ params, set }) => {
      const id = Number(params.id);
      const [row] = await db.select({ id: tags.id, archivedAt: tags.archivedAt })
        .from(tags).where(eq(tags.id, id));
      if (!row) { set.status = 404; return { error: "Tag not found" }; }
      if (row.archivedAt) { set.status = 409; return { error: "Already archived" }; }
      await db.update(tags).set({ archivedAt: sql`NOW()` }).where(eq(tags.id, id));
      return { ok: true };
    },
    {
      detail: {
        tags: ["tags"],
        summary: "Archive a tag",
        description:
          "Soft-deletes a tag by setting its `archivedAt` timestamp to the current UTC time.\n\n" +
          "Unlike classifications, archiving a tag is **not blocked** by existing bookmark associations — " +
          "the tag is archived immediately. Existing bookmark–tag links are preserved in the database " +
          "and the tag can be fully restored at any time via `PATCH /tags/:id/restore`.\n\n" +
          "Archived tags are excluded from `GET /tags` and are not counted in bookmark counts.",
        responses: {
          200: { ...OkResp, description: "Tag archived" },
          404: { ...ErrorResp, description: "Tag not found" },
          409: { ...ErrorResp, description: "Tag is already archived" },
        },
      },
    }
  )

  // ── Tags: PATCH /tags/:id/restore ─────────────────────────────────────────
  .patch(
    "/tags/:id/restore",
    async ({ params, set }) => {
      const id = Number(params.id);
      const [row] = await db.select({ id: tags.id, archivedAt: tags.archivedAt })
        .from(tags).where(eq(tags.id, id));
      if (!row) { set.status = 404; return { error: "Tag not found" }; }
      if (!row.archivedAt) { set.status = 409; return { error: "Not archived" }; }
      await db.update(tags).set({ archivedAt: null }).where(eq(tags.id, id));
      return { ok: true };
    },
    {
      detail: {
        tags: ["tags"],
        summary: "Restore an archived tag",
        description:
          "Clears the `archivedAt` timestamp on a tag, making it active again. " +
          "The tag reappears in `GET /tags` and all previously stored bookmark–tag associations " +
          "become visible again instantly.",
        responses: {
          200: { ...OkResp, description: "Tag restored to active" },
          404: { ...ErrorResp, description: "Tag not found" },
          409: { ...ErrorResp, description: "Tag is not archived" },
        },
      },
    }
  )

  // ── Classification Groups: POST /classifications/groups ───────────────────
  .post(
    "/classifications/groups",
    async ({ body, set }) => {
      const name = body.name.trim();
      if (!name) { set.status = 400; return { error: "name is required" }; }
      try {
        const [result] = await db
          .insert(classificationGroups)
          .values({ name, order: body.order ?? 0 })
          .$returningId();
        return { id: result.id, name, order: body.order ?? 0 };
      } catch (err: unknown) {
        if (isDupEntry(err)) { set.status = 409; return { error: "Group already exists" }; }
        throw err;
      }
    },
    {
      body: t.Object({
        name:  t.String({ description: "Group name. Must be unique among active groups. Whitespace is trimmed." }),
        order: t.Optional(t.Number({ description: "Display sort order. Lower numbers appear first. Defaults to 0." })),
      }),
      detail: {
        tags: ["groups"],
        summary: "Create a classification group",
        description:
          "Creates a new classification group used to organise related classifications.\n\n" +
          "Group names must be unique among **active** groups. Archived groups with the same name " +
          "do not block creation.\n\n" +
          "The `order` field controls the display position in the UI (lower = higher up the list). " +
          "Use `PATCH /classifications/groups/:id/reorder` to change order after creation.",
        responses: {
          201: {
            description: "Group created",
            content: {
              "application/json": {
                schema: S.obj("Created group", {
                  id:    S.num("New group ID"),
                  name:  S.str("Trimmed name as stored"),
                  order: S.num("Display sort order"),
                }),
              },
            },
          },
          400: { ...ErrorResp, description: "Validation error — name is blank after trimming" },
          409: { ...ErrorResp, description: "Conflict — an active group with this name already exists" },
        },
      },
    }
  )

  // ── Classification Groups: GET /classifications/groups ────────────────────
  .get(
    "/classifications/groups",
    async ({ query }) => {
      const includeArchived = query.archived === "true";
      const groupWhere = includeArchived ? undefined : isNull(classificationGroups.archivedAt);

      const [rows, classRows, countRows] = await Promise.all([
        db
          .select({
            id: classificationGroups.id,
            name: classificationGroups.name,
            order: classificationGroups.order,
            archivedAt: classificationGroups.archivedAt,
          })
          .from(classificationGroups)
          .where(groupWhere)
          .orderBy(classificationGroups.order, classificationGroups.name),
        // All classifications (active + archived) for these groups
        db
          .select({
            id: classifications.id,
            name: classifications.name,
            order: classifications.order,
            groupId: classifications.groupId,
            archivedAt: classifications.archivedAt,
          })
          .from(classifications)
          .orderBy(classifications.order, classifications.name),
        // Active bookmark counts per classification
        db
          .select({
            classificationId: bookmarkClassifications.classificationId,
            count: sql<number>`COUNT(*)`,
          })
          .from(bookmarkClassifications)
          .innerJoin(bookmarks, and(
            eq(bookmarkClassifications.bookmarkId, bookmarks.id),
            isNull(bookmarks.archivedAt)
          ))
          .groupBy(bookmarkClassifications.classificationId),
      ]);

      const countMap = new Map<number, number>(
        countRows.map((r) => [r.classificationId, Number(r.count)])
      );

      const items = rows.map((g) => ({
        ...g,
        classifications: classRows
          .filter((c) => c.groupId === g.id)
          .map((c) => ({ ...c, bookmarkCount: countMap.get(c.id) ?? 0 })),
      }));

      return { items };
    },
    {
      query: t.Object({
        archived: t.Optional(t.String({ description: "Pass `true` to include archived groups in the response. By default only active groups are returned." })),
      }),
      detail: {
        tags: ["groups"],
        summary: "List classification groups",
        description:
          "Returns groups with their nested classifications. " +
          "This is the **management view** — unlike `GET /classifications`, it includes both active and " +
          "archived classifications inside each group, and exposes the `archivedAt` field on both groups " +
          "and classifications so the UI can show archived state.\n\n" +
          "**Default:** active groups only. Pass `archived=true` to also include archived groups.\n\n" +
          "Each classification includes `bookmarkCount` reflecting only active (non-archived) bookmarks. " +
          "Groups are ordered by `order` then `name`; classifications within each group are ordered the same way.",
        responses: {
          200: {
            description: "Group list with nested classifications",
            content: {
              "application/json": {
                schema: S.obj("Groups management response", {
                  items: S.arr("List of groups", S.obj("Group with classifications", {
                    id:         S.num("Group ID"),
                    name:       S.str("Group name"),
                    order:      S.num("Display sort order"),
                    archivedAt: S.nullable(S.any("Archive timestamp (UTC), null when active")),
                    classifications: S.arr("Classifications in this group (active and archived)", S.obj("Classification", {
                      id:            S.num("Classification ID"),
                      name:          S.str("Classification name"),
                      order:         S.num("Display sort order"),
                      groupId:       S.nullable(S.num("Parent group ID")),
                      archivedAt:    S.nullable(S.any("Archive timestamp (UTC), null when active")),
                      bookmarkCount: S.num("Number of active bookmarks using this classification"),
                    })),
                  })),
                }),
              },
            },
          },
        },
      },
    }
  )

  // ── Classification Groups: PATCH /classifications/groups/:id (rename) ─────
  .patch(
    "/classifications/groups/:id",
    async ({ params, body, set }) => {
      const id = Number(params.id);
      const [row] = await db.select({ id: classificationGroups.id })
        .from(classificationGroups).where(eq(classificationGroups.id, id));
      if (!row) { set.status = 404; return { error: "Group not found" }; }
      const name = body.name.trim();
      if (!name) { set.status = 400; return { error: "name is required" }; }
      await db.update(classificationGroups).set({ name }).where(eq(classificationGroups.id, id));
      return { ok: true, id, name };
    },
    {
      body: t.Object({
        name: t.String({ description: "New group name. Must be non-empty after trimming. Does not need to be globally unique if the existing group is active." }),
      }),
      detail: {
        tags: ["groups"],
        summary: "Rename a classification group",
        description:
          "Updates the display name of a classification group. " +
          "The name is trimmed of leading/trailing whitespace before saving. " +
          "Works on both active and archived groups.",
        responses: {
          200: {
            description: "Group renamed",
            content: {
              "application/json": {
                schema: S.obj("Renamed group", {
                  ok:   { type: "boolean" as const, enum: [true], description: "Always true" },
                  id:   S.num("Group ID"),
                  name: S.str("New name as stored"),
                }),
              },
            },
          },
          400: { ...ErrorResp, description: "Validation error — name is blank after trimming" },
          404: { ...ErrorResp, description: "Group not found" },
        },
      },
    }
  )

  // ── Classification Groups: PATCH /classifications/groups/:id/reorder ──────
  .patch(
    "/classifications/groups/:id/reorder",
    async ({ params, body, set }) => {
      const id = Number(params.id);
      const [row] = await db.select({ id: classificationGroups.id })
        .from(classificationGroups).where(eq(classificationGroups.id, id));
      if (!row) { set.status = 404; return { error: "Group not found" }; }
      await db.update(classificationGroups).set({ order: body.order }).where(eq(classificationGroups.id, id));
      return { ok: true };
    },
    {
      body: t.Object({
        order: t.Number({ description: "New display sort order value. Lower numbers appear first. Values do not need to be contiguous." }),
      }),
      detail: {
        tags: ["groups"],
        summary: "Set display order for a classification group",
        description:
          "Sets the `order` field on a classification group, controlling its position in the UI. " +
          "Groups with lower `order` values appear first; ties are broken alphabetically by name.\n\n" +
          "Order values are arbitrary integers — you can use sparse values (e.g. 10, 20, 30) " +
          "to leave room for future insertions without having to reorder everything.",
        responses: {
          200: { ...OkResp, description: "Order updated" },
          404: { ...ErrorResp, description: "Group not found" },
        },
      },
    }
  )

  // ── Classification Groups: PATCH /classifications/groups/:id/archive ──────
  .patch(
    "/classifications/groups/:id/archive",
    async ({ params, set }) => {
      const id = Number(params.id);
      const [row] = await db.select({ id: classificationGroups.id, archivedAt: classificationGroups.archivedAt })
        .from(classificationGroups).where(eq(classificationGroups.id, id));
      if (!row) { set.status = 404; return { error: "Group not found" }; }
      if (row.archivedAt) { set.status = 409; return { error: "Already archived" }; }

      // Block if any active classification in the group has active bookmarks
      const [{ count }] = await db
        .select({ count: sql<number>`COUNT(*)` })
        .from(bookmarkClassifications)
        .innerJoin(bookmarks, and(
          eq(bookmarkClassifications.bookmarkId, bookmarks.id),
          isNull(bookmarks.archivedAt)
        ))
        .innerJoin(classifications, and(
          eq(bookmarkClassifications.classificationId, classifications.id),
          isNull(classifications.archivedAt),
          eq(classifications.groupId, id)
        ));
      const n = Number(count);
      if (n > 0) {
        set.status = 409;
        return { error: `Cannot archive: ${n} active bookmark${n === 1 ? "" : "s"} linked to classifications in this group` };
      }

      await db.update(classificationGroups).set({ archivedAt: sql`NOW()` }).where(eq(classificationGroups.id, id));
      return { ok: true };
    },
    {
      detail: {
        tags: ["groups"],
        summary: "Archive a classification group",
        description:
          "Soft-deletes a classification group by setting its `archivedAt` timestamp.\n\n" +
          "**Safety check:** archiving is blocked if any active (non-archived) classifications inside " +
          "this group have active bookmarks assigned to them. " +
          "The error message reports the total active bookmark count across all affected classifications.\n\n" +
          "To proceed: archive or reassign the bookmarks linked to this group's classifications first. " +
          "The group and all its classifications can be restored at any time.",
        responses: {
          200: { ...OkResp, description: "Group archived" },
          404: { ...ErrorResp, description: "Group not found" },
          409: { ...ErrorResp, description: "Already archived, or active bookmarks are linked to classifications in this group" },
        },
      },
    }
  )

  // ── Classification Groups: PATCH /classifications/groups/:id/restore ──────
  .patch(
    "/classifications/groups/:id/restore",
    async ({ params, set }) => {
      const id = Number(params.id);
      const [row] = await db.select({ id: classificationGroups.id, archivedAt: classificationGroups.archivedAt })
        .from(classificationGroups).where(eq(classificationGroups.id, id));
      if (!row) { set.status = 404; return { error: "Group not found" }; }
      if (!row.archivedAt) { set.status = 409; return { error: "Not archived" }; }
      await db.update(classificationGroups).set({ archivedAt: null }).where(eq(classificationGroups.id, id));
      return { ok: true };
    },
    {
      detail: {
        tags: ["groups"],
        summary: "Restore an archived classification group",
        description:
          "Clears the `archivedAt` timestamp on a classification group, making it active again.\n\n" +
          "Restoring a group does **not** automatically restore its archived classifications — " +
          "each classification must be restored individually via `PATCH /classifications/:id/restore` if needed.",
        responses: {
          200: { ...OkResp, description: "Group restored to active" },
          404: { ...ErrorResp, description: "Group not found" },
          409: { ...ErrorResp, description: "Group is not archived" },
        },
      },
    }
  )

  // ── Classifications: PATCH /classifications/:id (rename) ──────────────────
  .patch(
    "/classifications/:id",
    async ({ params, body, set }) => {
      const id = Number(params.id);
      const [row] = await db.select({ id: classifications.id })
        .from(classifications).where(eq(classifications.id, id));
      if (!row) { set.status = 404; return { error: "Classification not found" }; }
      const name = body.name.trim();
      if (!name) { set.status = 400; return { error: "name is required" }; }
      try {
        await db.update(classifications).set({ name }).where(eq(classifications.id, id));
        return { ok: true, id, name };
      } catch (err: unknown) {
        if (isDupEntry(err)) { set.status = 409; return { error: "Classification name already exists in this group" }; }
        throw err;
      }
    },
    {
      body: t.Object({
        name: t.String({ description: "New classification name. Must be non-empty after trimming. Must be unique within the same group among active classifications." }),
      }),
      detail: {
        tags: ["classifications"],
        summary: "Rename a classification",
        description:
          "Updates the display name of a classification. " +
          "The name is trimmed of whitespace before saving.\n\n" +
          "Uniqueness is enforced within the classification's group — the same name can exist in different groups. " +
          "Archived classifications with the same name in the same group do not cause a conflict.",
        responses: {
          200: {
            description: "Classification renamed",
            content: {
              "application/json": {
                schema: S.obj("Renamed classification", {
                  ok:   { type: "boolean" as const, enum: [true], description: "Always true" },
                  id:   S.num("Classification ID"),
                  name: S.str("New name as stored"),
                }),
              },
            },
          },
          400: { ...ErrorResp, description: "Validation error — name is blank after trimming" },
          404: { ...ErrorResp, description: "Classification not found" },
          409: { ...ErrorResp, description: "Conflict — an active classification with this name already exists in the same group" },
        },
      },
    }
  )

  // ── Classifications: PATCH /classifications/:id/reorder ───────────────────
  .patch(
    "/classifications/:id/reorder",
    async ({ params, body, set }) => {
      const id = Number(params.id);
      const [row] = await db.select({ id: classifications.id })
        .from(classifications).where(eq(classifications.id, id));
      if (!row) { set.status = 404; return { error: "Classification not found" }; }
      await db.update(classifications).set({ order: body.order }).where(eq(classifications.id, id));
      return { ok: true };
    },
    {
      body: t.Object({
        order: t.Number({ description: "New display sort order value. Lower numbers appear first within the group. Values do not need to be contiguous." }),
      }),
      detail: {
        tags: ["classifications"],
        summary: "Set display order for a classification",
        description:
          "Sets the `order` field on a classification, controlling its position within its group in the UI. " +
          "Classifications with lower `order` values appear first; ties are broken alphabetically by name.\n\n" +
          "Order values are arbitrary integers — sparse values (e.g. 10, 20, 30) are recommended " +
          "to minimise the need to reorder multiple items at once.",
        responses: {
          200: { ...OkResp, description: "Order updated" },
          404: { ...ErrorResp, description: "Classification not found" },
        },
      },
    }
  )

  // ── Backup ─────────────────────────────────────────────────────────────────
  // GET /backup   (Authorization: Bearer <BACKUP_TOKEN>)
  // Streams a gzip-compressed mariadb-dump of the bookmarks database.
  // The BACKUP_TOKEN env var must be set to a non-default value.
  .get(
    "/backup",
    async ({ headers, set }) => {
      const configuredToken = process.env.BACKUP_TOKEN ?? "";

      // Refuse if the token is unset or still the placeholder
      if (!configuredToken || configuredToken === "change_me_please") {
        set.status = 503;
        return {
          error:
            "Backup is not configured. Set BACKUP_TOKEN to a strong random value in api/.env and restart the service.",
        };
      }

      // Extract Bearer token from Authorization header
      const authHeader = headers["authorization"] ?? "";
      const bearerMatch = authHeader.match(/^Bearer\s+(.+)$/i);
      const providedToken = bearerMatch ? bearerMatch[1] : "";

      if (!providedToken || providedToken !== configuredToken) {
        set.status = 401;
        return { error: "Invalid or missing backup token. Send header: Authorization: Bearer <BACKUP_TOKEN>" };
      }

      const dbHost     = process.env.DB_HOST     ?? "127.0.0.1";
      const dbPort     = process.env.DB_PORT      ?? "3306";
      const dbUser     = process.env.DB_USER      ?? "bookmark";
      const dbPassword = process.env.DB_PASSWORD  ?? "";
      const dbName     = process.env.DB_NAME      ?? "bookmarks";

      const timestamp  = new Date()
        .toISOString()
        .replace(/T/, "_")
        .replace(/:/g, "")
        .slice(0, 15); // YYYY-MM-DD_HHMMSS
      const filename   = `bookmark_${timestamp}.sql.gz`;

      // Run mariadb-dump (installed in this container) against the pod-internal DB
      const dump = Bun.spawn(
        [
          "mariadb-dump",
          `--host=${dbHost}`,
          `--port=${dbPort}`,
          `--user=${dbUser}`,
          `--password=${dbPassword}`,
          "--single-transaction",
          "--routines",
          "--triggers",
          dbName,
        ],
        { stdout: "pipe", stderr: "pipe" }
      );

      const gz = Bun.spawn(["gzip", "-9"], {
        stdin: dump.stdout,
        stdout: "pipe",
        stderr: "pipe",
      });

      const exitCode = await dump.exited;
      if (exitCode !== 0) {
        const errText = await new Response(dump.stderr).text();
        set.status = 500;
        return { error: `mysqldump failed (exit ${exitCode}): ${errText.trim()}` };
      }

      const gzBuffer = await new Response(gz.stdout).arrayBuffer();

      return new Response(gzBuffer, {
        headers: {
          "Content-Type": "application/gzip",
          "Content-Disposition": `attachment; filename="${filename}"`,
          "Cache-Control": "no-store",
        },
      });
    },
    {
      detail: {
        tags: ["backup"],
        summary: "Download a database backup",
        description:
          "Streams a gzip-compressed `mariadb-dump` of the full bookmarks database.\n\n" +
          "**Authentication:** send the token in the `Authorization` header as a Bearer token:\n" +
          "```\nAuthorization: Bearer <BACKUP_TOKEN>\n```\n" +
          "where `BACKUP_TOKEN` is set in `api/.env`.\n\n" +
          "The endpoint returns `503` if the token is unset or still the default placeholder, " +
          "and `401` if the token is missing or does not match.\n\n" +
          "The response is a `.sql.gz` file attachment named `bookmark_YYYY-MM-DD_HHMMSS.sql.gz`.",
        responses: {
          200: { description: "SQL dump (gzip-compressed) file download" },
          401: { ...ErrorResp, description: "Missing or invalid Authorization header" },
          503: { ...ErrorResp, description: "Backup not configured — set BACKUP_TOKEN in api/.env" },
        },
      },
    }
  )

  // ── Start ──────────────────────────────────────────────────────────────────
  .listen(PORT);

console.log(
  `🔖 Bookmark Manager API running at http://localhost:${PORT}\n` +
    `   Viewer UI  → http://localhost:${PORT}/app\n` +
    `   Swagger UI → http://localhost:${PORT}/docs\n` +
    `   OpenAPI    → http://localhost:${PORT}/openapi.json`
);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function isDupEntry(err: unknown): boolean {
  return (
    typeof err === "object" &&
    err !== null &&
    "code" in err &&
    err.code === "ER_DUP_ENTRY"
  );
}

export type App = typeof app;
