version: '3.8'
services:
  api:
    build: .
    container_name: bm_api_prod
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    command: sh -c "npm run migrate && npm start"
    restart: unless-stopped

